import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Theme radius="full">
        {children}
        </Theme>
        </body>
    </html>
  )
}
